import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';

import { TRPCReactProvider } from '@/trpc/client';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';

const font = DM_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Multitenant Ecommerce App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${font.className} antialiased`}>
        <TRPCReactProvider>
          {children}
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
