import { Toaster } from '@/components/ui/sonner';
import { TRPCReactProvider } from '@/trpc/client';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import './globals.css';

const font = DM_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Paloemango Ecommerce App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Content passed from each route
}>) {
  return (
    <html lang='en'>
      <body className={`${font.className} antialiased`}>
        {/* Enables URL state syncing for filters and other query params */}
        <NuqsAdapter>
          {/* Wrap all content in tRPC provider for API access */}
          <TRPCReactProvider>
            {children}
            {/* Global toast notifications */}
            <Toaster />
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
